export type MediaType = 'movie' | 'tv'

/**
 * A title as the UI needs it.
 *
 * Fields sourced from TMDB (title, poster, runtime, genres, credits) are for
 * DISPLAY ONLY and must never be placed into an AI prompt — see
 * docs/DECISIONS.md, "AI firewall".
 */
export interface Title {
  id: string
  tmdbId: number | null
  mediaType: MediaType
  name: string
  year: number
  /** Full TMDB image URL, or null while we have no API key wired up. */
  posterUrl: string | null
  runtimeMinutes: number | null
  /** Number of seasons, for mediaType 'tv'. We deliberately do not track episodes. */
  seasons: number | null
  genres: string[]
  director: string | null
  /** Age certification for the viewer's country, e.g. "15", "PG-13". */
  certification: string | null
}

/**
 * A recommendation. `reason` is generated by our own model call and is NOT
 * TMDB content, so it is safe to translate and to store indefinitely.
 */
export interface Recommendation {
  title: Title
  reason: string
}
